### PR TITLE
WIP: Path to array

### PR DESCRIPTION
**Pull request by LukasBoll**

### CODE REVIEW

**Comment by sdirix** [comment]
Hi @LukasBoll ! The current state sadly doesn't run for me. Executing `npm ci && npm run init && npm run build` fails at the build step for the Vue packages. When I manually build `core`, `angular` and `angular-material` and start the example app then the forms don't render at all but crash with numerous exceptions. Can you take a look?

**Comment by LukasBoll** [comment]
@sdirix Sorry, I switched between branches and somehow lost my latest changes in the process. Should work now.

**Comment by lepffm** [comment]
Has the "dot-seperated" issue been resolved yet?

**Comment by sdirix** [comment]
We came up with a better solution, documented it in #2153 and will start developing it soon. Therefore I'll close this PR as it's outdated.

**Pull request closed without merging**
