### PR TITLE
Use aria-describedby on checkboxes with descriptions

### LINKED ISSUE #2078: Screenreader support on MUI checkboxes with descriptions
### Is your feature request related to a problem? Please describe.

The descriptions of checkboxes are not read by screenreaders. This means that non-sighted users will not benefit from checkbox help text when using the form.

### Describe the solution you'd like

The checkbox should use [aria-describedby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby) and reference the help text elements so that screenreaders will read them.

### Describe alternatives you've considered

I'm not aware of other solutions.

### Framework

React

### RendererSet

Material

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #2078 

I should note that the problem this solves also affects other components, like the text input. But I wanted to start with a simpler case (checkboxes) before tackling that one, to make sure the team is OK with this approach.

### CODE REVIEW

**Comment by sdirix** [comment]
Thanks for the contribution!

**Comment by brockfanning** [comment]
@sdirix No problem! I need to make the same type of change for text inputs, but I wanted to make sure this approach (passing along the inputProps) is OK with you. Should I proceed?

**Review by sdirix — APPROVED** [review]
Thanks again! The code looks good.

I thought about whether it's worth to `useMemo` the inputProps objects but I actually think it's not necessary here. In almost all use cases the memo will not apply.

The only use case I could think off is when someone updates the JSON Schema at runtime with a new description. This is really an edge case, and if someone does that they probably don't care that the input is also rerendered (maybe there is even some additional memo barrier further within Material UI)

So the code looks good! However it would be nice if you could add test cases

**Comment by sdirix** [comment]
@brockfanning Will you add a testcase?

**Comment by brockfanning** [comment]
@sdirix I just pushed up a couple of tests - please let me know if that is not what you had in mind. I only did tests for MaterialBooleanToggleControl because I did not see any existing tests for MaterialBooleanControl. Did I miss those?

**Comment by sdirix** [comment]
Thanks for the contribution :heart: ;)

**Pull request merged**
