### PR TITLE
(Draft) angular/angular-material 13

### LINKED ISSUE #1993: Angular Ivy distribution
### Is your feature request related to a problem? Please describe.

When compiling a project depending on `@jsonforms/angular` (and `@jsonforms/angular-material`), the CLI output the following message:

```
Processing legacy "View Engine" libraries:
- @jsonforms/angular [module/esm5] (https://github.com/eclipsesource/jsonforms)
- @jsonforms/angular-material [module/esm5] (https://github.com/eclipsesource/jsonforms)
Encourage the library authors to publish an Ivy distribution.
```

### Describe the solution you'd like

Updating both package to angular 13 (or more) will solve this issue by setting `"compilationMode": "partial"` in `tsconfig.lib.prod.json`

### Describe alternatives you've considered

None

### Framework

Angular

### RendererSet

Material

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JBBianchi**
An attempt to migrate angular related packaged to v13 for full Ivy support.

**Changes applied:**
- (angular/angular-material) Migrated to Angular 13
- (all) Migrated to TypeScript 4.6.4
- (material) Fixed implicit `any` type

**Notes:**
`@jsonforms/material-renderers` tests are failing.

Closes #1993

### CODE REVIEW

**Comment by sdirix** [comment]
Thank you for the PR! We'll take a look soonish!

**Comment by JBBianchi** [comment]
thanks @sdirix , let me know if I can help.

**Review by sdirix — CHANGES_REQUESTED** [review]
Did you test the built Angular components in practice? At least the Angular example app (`npm run dev` in `packages/angular-material` no longer works.

For this to be merged:
 - All example apps within this repository must work
 - The broken test cases must be fixed
 - The [Angular seed](https://github.com/eclipsesource/jsonforms-angular-seed) must be able to consume the new modules and continue to work

**Comment by sdirix** [comment]
I fixed all minor comments I discovered during my review, however the major points still need to be addressed:

 - All example apps within this repository must work
 - The broken test cases must be fixed
 - The [Angular seed](https://github.com/eclipsesource/jsonforms-angular-seed) must be able to consume the new modules and continue to work

**Comment by JBBianchi** [comment]
As the tests for `@jsonforms/material-renderers` were failing, I didn't go further yet and run examples/seeds. I'll have a look at the angular/angular-material ones.

**Comment by JBBianchi** [comment]
I tried to progress on bit on that task recently but I'm running into issues with typedoc (need to remove the theme/ignoreCompilerErrors for instance) and vue conflicting versions.

**Pull request closed without merging**
