### PR TITLE
Angular 18 Update

### PR DESCRIPTION
**Pull request by lucas-koehler**
Based on PR #2337 extended by using the Angular 18 release and regenerated pnpm lock file by me.

### CODE REVIEW

**Comment by lucas-koehler** [comment]
@laurentgrangier Please confirm whether JsonForms works for you with Angular 18 in this state. If yes, we'll merge this and do a release soon.

**Comment by lucas-koehler** [comment]
@sdirix Good point! I added a Json Forms 3.3 section mentioning this to MIGRATION.md

**Comment by laurentgrangier** [comment]
@lucas-koehler Thank you for the new PR and the upgrade to Angular 18 final version. I check JsonForms with Angular 18 and give you feedback quickly (should be this week).

**Comment by laurentgrangier** [comment]
@lucas-koehler I tested JSONForms built on this branch with our software using Angular 17 and also using Angular 18 and had no problem with JSONForms. We only use jsonforms/core and jsonforms/angular. No other packages of jsonforms.

**Review by sdirix — APPROVED** [review]

**Comment by sdirix** [comment]
I also tested with React 18 in the Angular Seed application. That works :+1:

**Pull request merged**
