### PR TITLE
Added Autocomplete Renderer

### PR DESCRIPTION
**Pull request by eneufeld**
The renderer must be registered and added to the module.

* includes renderer
* includes tests

### CODE REVIEW

**Comment by edgarmueller** [comment]
@eneufeld The implementation LGTM, but could you outline what steps are necessary to include in the dev example (what modules do I need to import, what renderer etc.)? Ideally, this should be documented somewhere (e.g. JsDoc).

**Comment by eneufeld** [comment]
makes sense, will do

**Comment by edgarmueller** [comment]
Thanks! I followed the JsDoc and adapted the person example to use this renderer for the nationality property. I'm experiencing some issues though

1. It looks kinda off
selection_085

2. Selecting entries doesn't seem to work, regardless whether I click confirm them by clicking or pressing enter. The completion box just stays open:

selection_086

3.console errors popping up (might be related to the previous errors)
```
AutocompleteControlRenderer.html:2 ERROR Error: mat-form-field must contain a MatFormFieldControl.
    at getMatFormFieldMissingControlError (form-field.es5.js:110)
    at MatFormField._validateControlChild (form-field.es5.js:636)
    at MatFormField.ngAfterContentChecked (form-field.es5.js:426)
    at callProviderLifecycles (core.js:12744)
    at callElementProvidersLifecycles (core.js:12715)
    at callLifecycleHooksChildrenFirst (core.js:12698)
    at checkAndUpdateView (core.js:13848)
    at callViewAction (core.js:14195)
    at execComponentViewsAction (core.js:14127)
    at checkAndUpdateView (core.js:13850)
```

**Comment by eneufeld** [comment]
hmm, i will recheck

**Comment by edgarmueller** [comment]
@eneufeld Did we update this already to include the missing module (I forgot which one it was).

**Comment by eneufeld** [comment]
no we didn't we created this issue #1126

**Comment by edgarmueller** [comment]
We'll need to fix the form binding (as a follow-up PR), but that also affects other controls, hence this I'm good with the change.

**Pull request merged**
