### PR TITLE
added categorization expandbar renderer

### PR DESCRIPTION
**Pull request by eneufeld**
Added additional renderer for categories as expandbars instead of tabs

### CODE REVIEW

**Comment by edgarmueller** [comment]
This one probably needs to be updated once #268 has been merged.

**Comment by edgarmueller** [comment]
@eneufeld Do we need to update this PR?

**Comment by eneufeld** [comment]
It is not important and as far as I can recall not used anywhere.
I will update it when I have some time.

**Comment by eneufeld** [comment]
@edgarmueller can you take a look at this?
- rebased
- moved renderer to bootstrap

**Comment by edgarmueller** [comment]
The regular case (`dev`) works fine, but the bootstrap renderer renders an empty form on the right-hand side  for me:

pr253

Do you experience this as well?

The material renderer ignores the custom `expandbar` option altogether, but I suppose this is intended behaviour.

**Comment by eneufeld** [comment]
Yes, 
the problem is, that this renderer expects a specific structure of the categorization.
The current example doesn't fit. 
I will update the code and provide a dedicated example for this renderer.

**Comment by eneufeld** [comment]
@edgarmueller 
I created a dedicated example, this must be refactored when we singlesource the examples.

**Pull request merged**
