### PR TITLE
Add support for "multiple" prop on Select (fixes #2347)

### LINKED ISSUE #2347: Support for `multiple` prop on `Select`
### Is your feature request related to a problem? Please describe.

I would like to use MUI's `Select` component, but with the `multiple` flag enabled. See https://mui.com/material-ui/react-select/#multiple-select. Unfortunately, the `MuiSelect` component in the material renderers does not accept the `multiple` prop no provide any way to pass it to the underlying `Select`.

### Describe the solution you'd like

Locally I've added a new interface to `material-renderers/src/util/theme.ts`:

```ts
export interface WithSelectProps {
  multiple?: boolean;
}
```

Then added it to the `MuiSelect` component:
```diff
-import { i18nDefaults, WithInputProps } from '../util';
+import { i18nDefaults, WithInputProps, WithSelectProps } from '../util';
 
 export const MuiSelect = React.memo(function MuiSelect(
-  props: EnumCellProps & WithClassname & TranslateProps & WithInputProps
+  props: EnumCellProps & WithClassname & TranslateProps & WithInputProps & WithSelectProps
 ) {
   const {
     data,
@@ -46,6 +46,7 @@ export const MuiSelect = React.memo(function MuiSelect(
     config,
     label,
     t,
+    multiple,
   } = props;
   const appliedUiSchemaOptions = merge({}, config, uischema.options);
   const noneOptionLabel = useMemo(
@@ -63,6 +64,7 @@ export const MuiSelect = React.memo(function MuiSelect(
       value={data !== undefined ? data : ''}
       onChange={(ev) => handleChange(path, ev.target.value || undefined)}
       fullWidth={true}
+      multiple={multiple}
     >
```

This worked perfectly for me. I'm not sure if this is the right approach, but could something like this be considered for inclusion?

### Describe alternatives you've considered

MUI's `Autocomplete` can do some of this, but it's overly complicated for most of my use cases and it can be confusing to users who are expecting normal `<select>`-like behavior.

### Framework

React

### RendererSet

Material

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jchamberlain**
Here are the changes proposed in #2347.

### CODE REVIEW

**Review by lucas-koehler — COMMENTED** [review]
Hi @jchamberlain , thanks for the contribution :heart: 
The changes LGTM. Could you pleaserebase them onto the current master to get a (hopefully) clean run of the CI? Thanks!

**Comment by lucas-koehler** [comment]
@jchamberlain I rebased the changes with Github's builtin functionality. The lint check fails because `MuiSelect` is not formatted properly. Please apply the formatting accordingly :)

**Comment by jchamberlain** [comment]
Hey @lucas-koehler, formatting applied.

**Review by lucas-koehler — APPROVED** [review]
LGTM now. Thanks again for the contribution :)

**Comment by jchamberlain** [comment]
Thanks, @lucas-koehler! I was going to start using it in my project directly via the master branch, but my ancient version of yarn doesn't like your monorepo (and I can't upgrade yarn just yet). How soon will you be publishing a new release tag? Anything that publishes the individual packages to NPM will work for me. Perhaps you could publish an alpha or beta?

**Comment by lucas-koehler** [comment]
Hi @jchamberlain , I published a new alpha `3.4.0-alpha.1`

**Comment by jchamberlain** [comment]
Perfect. Thank you!

**Pull request merged**
