### PR TITLE
Fix trimming a text input for Material

### PR DESCRIPTION
**Pull request by 1903Daniel**
@edgarmueller @eneufeld 
please review

### CODE REVIEW

**Comment by 1903Daniel** [comment]
@edgarmueller @eneufeld 
I think the travis build is set up inaccurately. Can you please check?
(see also https://github.com/eclipsesource/jsonforms/pull/858)
build & test work locally, but not on travis

lerna ERR! > @2.0.0-rc.1 build /home/travis/build/eclipsesource/jsonforms/packages/core
lerna ERR! > ../../node_modules/.bin/tsc
lerna ERR!
lerna ERR! ../../node_modules//index.d.ts(12651,53): error TS2344: Type 'T' does not satisfy the constraint 'object'.

**Comment by eneufeld** [comment]
Try fixing lodash to version 4.17.4 .
I think there is a bug in the lodash typings due to the typescript 2.7 release.
If this doesn't help, then also fix typescript to 2.6.2

**Comment by 1903Daniel** [comment]
@eneufeld I tried both in #858. Fixing ts removed that error, but another occured, which we also saw on Ahmet's Mac today when we tried an example for our demo with an older version of the branch (around 11 Jan). We couldn't figure that one out, as clearly these props should exist on the material component:

lerna ERR! src/complex/TableToolbar.tsx(25,25): error TS2339: Property 'type' does not exist on type 'IntrinsicAttributes & TypographyProps & { children?: ReactNode; }'.
lerna ERR! src/complex/TableToolbar.tsx(35,21): error TS2339: Property 'fab' does not exist on type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.
lerna ERR! src/complex/TableToolbar.tsx(47,21): error TS2339: Property 'fab' does not exist on type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.

**Comment by eneufeld** [comment]
Check the package.json files as they are configured right now on master.
We had to pin multiple versions to fix build errors.

**Comment by edgarmueller** [comment]
Closed in favor of #893

**Pull request closed without merging**
