### PR TITLE
Add Live-Playground link to README file

### PR DESCRIPTION
**Pull request by mirismaili**
I developed this tool to the order of the company I work in. Other users can use this useful tool too.

### CODE REVIEW

**Comment by mirismaili** [comment]
image

**Comment by sdirix** [comment]
The playground looks nice! Good work! :+1: If you'd like we can give you a shout out via our twitter.

I'll discuss with the team whether and how we want to handle links from the main repository to external resources which we can't control.

**Comment by mirismaili** [comment]
@sdirix 
Thank you. I don't have a Twitter account. 

I can move the repository everywhere you want.

**Comment by sdirix** [comment]
Hi @mirismaili I'll close this PR now as we are in the process of adding a Community page to the website.

I wanted to add the link to your playground too, however the playground seems to be broken at the moment. If you have time it would be great if you could fix it. I would then add your link to the [PR](https://github.com/eclipsesource/jsonforms2-website/pull/252).

**Pull request closed without merging**
