### PR TITLE
Use immutable set instead of cloneDeep

### PR DESCRIPTION
**Pull request by DavidHenri008**
Replace cloneDeep by loadash/fp set in UPDATE_DATA core reducer.
Update core reducer tests.

### CODE REVIEW

**Comment by DavidHenri008** [comment]
Since I am developing on Windows, I wasn't able to run all tests and build sequences.

**Review by AlexandraBuzila — APPROVED** [review]
LGTM!

**Comment by DavidHenri008** [comment]
Am I supposed to close the PR in order to merge it?

**Comment by sdirix** [comment]
@DavidHenri008 We'll manually merge this soon ;)

**Review by sdirix — APPROVED** [review]
LGTM

**Pull request merged**
