### PR TITLE
﻿fix(translations): memoize array translation

### PR DESCRIPTION
**Pull request by LukasBoll**
This commit addresses an issue where array translations were created as new objects within the core module for each render cycle, causing unnecessary rerenders. By memoizing the translation object in the material renderer set, this commit optimizes performance and prevents redundant rerenders.

### CODE REVIEW

**Comment by sdirix** [comment]
@LukasBoll Can you fix the build or do you need support?

**Comment by LukasBoll** [comment]
Hi @sdirix,
I just fixed the build issues :)

**Review by sdirix — CHANGES_REQUESTED** [review]
The PR looks good in general. However there seems to be an issue in Vue Vanilla. When checking the "Nested arrays" example and adding a new element to the outer array, then the nested array within it crashes. Can you check what's going on?

This is the error message:
>TypeError: Cannot read properties of undefined (reading 'noDataMessage')
    at Proxy.render$l (ArrayListRenderer.vue:44:31)
    at renderComponentRoot (runtime-core.esm-bundler.js:887:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:6020:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
    at instance.update (runtime-core.esm-bundler.js:6151:16)
    at setupRenderEffect (runtime-core.esm-bundler.js:6161:5)
    at mountComponent (runtime-core.esm-bundler.js:5929:7)
    at processComponent (runtime-core.esm-bundler.js:5883:9)
    at patch (runtime-core.esm-bundler.js:5351:11)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:6027:11)

**Comment by sdirix** [comment]
@LukasBoll Can you resolve the conflicts?

**Review by sdirix — APPROVED** [review]

**Comment by lucas-koehler** [comment]
Merge commit only fixes a tiny merge conflict.

**Pull request merged**
