### PR TITLE
possibility to add our own ajv config

### PR DESCRIPTION
**Pull request by GabinH**

### CODE REVIEW

**Comment by edgarmueller** [comment]
@GabinH Thanks for contribution! LGTM (although we should probably move the validator out of the store at some point) @eneufeld What do you think?

**Comment by eneufeld** [comment]
@edgarmueller I agree with you, we should open a follow up issue to move the validator, but we can merge it in the meantime

**Comment by edgarmueller** [comment]
@GabinH Mind if you rebase your change, such that we can merge it? Thanks :)

**Comment by GabinH** [comment]
@edgarmueller  What do you mean by rebase my change ?

**Comment by edgarmueller** [comment]
There are conflicting files, see `packages/core/src/actions/index.ts`

**Comment by edgarmueller** [comment]
Something went wrong with your rebase, I did it for you, see #1088. I'm closing this one therefore.

**Pull request closed without merging**
