### PR TITLE
Fixes group's label being reformatted with startCase

### PR DESCRIPTION
**Pull request by sifthedog**

### CODE REVIEW

**Review by sdirix — COMMENTED** [review]
This certainly improves the current situation but we probably shouldn't change the label unconditionally, i.e. this still overrides the label which is manually set on a group detail.

**Review by sdirix — APPROVED** [review]

**Comment by sdirix** [comment]
I opened a follow up: #1712

**Comment by sifthedog** [comment]
@sdirix need a hand with the follow up? Let me know if I can help in any way.

**Comment by sdirix** [comment]
> @sdirix need a hand with the follow up? Let me know if I can help in any way.

Sure that would be great ;) The main problem here is that `findUISchema` doesn't indicate whether it generated or found the ui schema. In the latter case we should not modify it. Also any change should be backwards compatible.

**Pull request merged**
