### PR TITLE
Allow the translation of the No Data case for MaterialArrayLayout

### PR DESCRIPTION
**Pull request by Maxouwell**
Tentative PR for #2285

### CODE REVIEW

**Comment by lucas-koehler** [comment]
Hi @Maxouwell , thanks for the PR :heart: We'll have a look soon.

**Review by sdirix — APPROVED** [review]
Looks good! Thanks for the contribution :heart:

**Comment by sdirix** [comment]
@Maxouwell There is still some type error in the test, can you take a look?

**Comment by Maxouwell** [comment]
Lookink into it, but I'm kind of puzzled why test are failing in core while I modified only the material package

**Comment by Maxouwell** [comment]
I can't reproduct the error on my side, I explicitly made the array data an `any[]` type to look if it please jest

**Pull request merged**
