### PR TITLE
Show unfocused description config

### PR DESCRIPTION
**Pull request by Lily418**
I was doing user testing yesterday and found the user didn't know what unit one of the inputs required, this was it the description but this only showed when they focused the field.

I'd like the option to show unfocused helper text.
Screenshot 2019-06-21 at 15 38 16

### CODE REVIEW

**Comment by eneufeld** [comment]
I agree the new option would be useful. I would not mix in commit 1b8d51fe53a0b6322b4bb528a547e853405a5b48 (which is pr #1413 ) into this though.

**Comment by Lily418** [comment]
@eneufeld opps, that wasn't meant to be there. Thanks have updated now.

**Comment by eneufeld** [comment]
@edgarmueller what is your take on this? I think this is a nice extension.

**Comment by edgarmueller** [comment]
I agree, actually we have the same requirement in another project, so I'm all in favor for it!

**Comment by edgarmueller** [comment]
On a sidenote: this adds to the long list of TODOs about documentation, I've updated https://github.com/eclipsesource/jsonforms/issues/1203 accordingly

**Pull request merged**
