### PR TITLE
Encode '/' in prop name

### PR DESCRIPTION
**Pull request by max-elia**
- Encode '/' in ui schema generator
- Decode '/' and '~' in:
  - Resolvers
  - Label
  - MaterialTableControl
  - Vanilla TableArrayControl
  - Angular table.renderer
- Add test cases for uischema, resolver and path

Signed-off-by: Max Elia Schweigkofler <max_elia@hotmail.de>

### CODE REVIEW

**Review by TheZoker — CHANGES_REQUESTED** [review]
Thanks for the PR 👍 
For most cases this works well, but as soon as there is an array involved , there seems to be no input anymore:
image

image

**Comment by max-elia** [comment]
Thanks, for the feedback. Array's are now also work fine and tests have been added.

**Review by TheZoker — APPROVED** [review]
LGTM 👍 Array example works now

**Review by sdirix — APPROVED** [review]
LGTM!

**Pull request merged**
