### PR TITLE
Fix type-imports according to the release notes of TypeScript 3.8

### PR DESCRIPTION
**Pull request by mirismaili**
See: [Type-Only Imports and Export](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)

### CODE REVIEW

**Comment by sdirix** [comment]
Hi @mirismaili, thanks for the PR. Can you tell about the motivation? Do you run into problems when not refactoring those specific type imports/exports?

**Comment by mirismaili** [comment]
Hi @sdirix 

Your welcome.

I was trying to add some unsupported features to the library (`additionalProperties` and `patternProperties` / #1765) for our business. So I created a dev-project that I can test my changes into the library, quickly (using hot-reload). 

My different webpack/typescript configuration (at the dev-project) causes some issues. I fixed them (there) to match JSONForms. But this special case was an issue in JSONForms. So I decided to fix it here.
***
I also created a playground for JSONForms (#1841).

**Comment by mirismaili** [comment]
I think the below configuration can be changed after this fix (be applied to all packages):

https://github.com/eclipsesource/jsonforms/blob/6bcdbb171846ba19121aa3f93d087778611dde7e/webpack/webpack.base.js#L25

But I'm not sure.

**Comment by sdirix** [comment]
@mirismaili The PR conflicts now, can you rebase on latest master?

**Comment by mirismaili** [comment]
@sdirix 
Rebased.

**Review by sdirix — APPROVED** [review]
LGTM!

**Pull request merged**
