### PR TITLE
Fix "dot-separated" paths by making paths type `string[]` (instead of `string`)

### PR DESCRIPTION
**Pull request by mirismaili**
Fix "dot-separated" paths by making paths type `string[]` (instead of `string`) for react (in these packages: **"core"**, **"react"** and **"material-renderers"**)

eclipsesource/jsonforms#1849
eclipsesource/jsonforms#1831

### CODE REVIEW

**Comment by mirismaili** [comment]
I know this can't be merged now. Because of conflicts with unfixed packages (angular, vue, ...). But those can be fixed, as well.

**Comment by sdirix** [comment]
Hi @mirismaili, thanks for the PR. We're already working on this, see https://github.com/eclipsesource/jsonforms/pull/1831

The main problem with the array approach is to not lose performance. Just replacing strings with arrays here will lead to massive degradation as the memoization of React will no longer work and therefore the whole form will rerender with every change.

**Comment by lepffm** [comment]
Hi, Has the "dot-seperated" issue been resolved yet?

**Comment by sdirix** [comment]
We came up with a better solution, documented it in #2153 and will start developing it soon. Therefore I'll close this PR as it's outdated.

**Pull request closed without merging**
